Repository sclorg/nginx-container, pull requests merged in 2024-06, with the labels that each got.

#299 deprecate c8s images, as EOL for c8s is 31th of May 2024
  .github/workflows/build-and-push.yml
  1.22-micro/README.md
  1.24/.exclude-c8s
  1.24/README.md
  README.md
Labels: ready for review

#298 Add support for testing Nginx 1.26 as container as openshift
  .github/workflows/container-tests.yml
  .github/workflows/openshift-tests.yml
Labels: ready for review

#302 Add file show_all_imagestreams.py from container-common-scripts
  test/show_all_imagestreams.py
Labels: ready for review, easyfix

#303 Add GitHub Action for running testing written in PyTest
  .github/workflows/openshift-pytests.yml
Labels: enhancement, ready for review, easyfix
